import Footer from "../footer/Footer";
import Navbar from "../navbar/Navbar";
import React from 'react'
import styles from './Layaout.module.scss'
import Head from 'next/head'

const Layout = ({children}) => {
  return (
    <div className={styles.container_layout}>
      <Head>
        <title>Restoner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/restoner.ico" />
      </Head>
        <Navbar/>
        {children}
        <Footer/>
    </div>
  )
}

export default Layout